# inspired by: https://github.com/actions/checkout/blob/44c2b7a8a4ea60a981eaca3cf939b5f4305c123b/action.yml

name: 'Checkout'
description: 'Ostensibly, checkout a Git repository'

inputs:

  repository:
    default: ${{ github.repository }}

  ref: {}

  token:
    default: ${{ github.token }}

  path: {}

  clean:
    default: true

  fetch-depth:
    description: 'number of commits; 0 for all'
    default: 1

  set-safe-directory:
    default: true

runs:
# TODO this should simply be "composite" instead, or have a separate "docker" version somehow, but that makes the post-run cleanup harder (as composite actions don't have a "post" step like Docker and Node.js actions do; https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions; https://github.com/actions/runner/issues/1478)
  using: docker
  image: Dockerfile
  entrypoint: checkout.sh
  post-entrypoint: cleanup.sh
  env:
    # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions:~:text=inputs%20using%20the-,INPUT_NUM%2DOCTOCATS,-and%20INPUT_OCTOCAT%2DEYE is cursed ("INPUT_FETCH-DEPTH" can't easily be used from bash 🙃)
    INPUT_FETCH_DEPTH: '${{ inputs.fetch-depth }}'
    INPUT_SET_SAFE_DIRECTORY: '${{ inputs.set-safe-directory }}'
